"""Compatibility exports for the split OCR client modules.

The command-line entry points historically imported the lib module directly.
Keep this small facade so those callers can migrate independently while the
implementation lives in cohesive modules.
"""

from config import (
    API_GUIDE_URL,
    DEFAULT_CONFIG_PATH,
    DEFAULT_CONNECT_TIMEOUT,
    DEFAULT_KEYCHAIN_ACCOUNT,
    DEFAULT_KEYCHAIN_SERVICE,
    DEFAULT_LARGE_FILE_WARNING_MB,
    DEFAULT_MAX_LOCAL_FILE_MB,
    DEFAULT_MAX_REQUEST_MB,
    DEFAULT_MAX_RESPONSE_MB,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_BACKOFF,
    DEFAULT_CACHE_MAX_MB,
    DEFAULT_CACHE_TTL_SECONDS,
    DEFAULT_MAX_CHUNK_WORKERS,
    DEFAULT_MAX_PAGES_PER_REQUEST,
    LOCAL_CONFIG_KEYS,
    DEFAULT_MODEL,
    DEFAULT_TASK_TIMEOUT,
    DEFAULT_TIMEOUT,
    FILE_TYPE_IMAGE,
    FILE_TYPE_PDF,
    IMAGE_EXTENSIONS,
    MAX_LOCAL_FILE_BYTES,
    MAX_REQUEST_BYTES,
    MAX_RESPONSE_BYTES,
    MAX_RETRY_AFTER_SECONDS,
    MAX_TASK_TIMEOUT,
    MAX_CACHE_MAX_MB,
    MAX_CHUNK_WORKERS,
    SUPPORTED_FILE_TYPES,
    _get_access_token,
    _get_env,
    _get_float_env,
    _get_int_env,
    _get_keychain_secret,
    _get_local_config,
    _get_setting,
    _keychain_enabled,
    _metric_add,
    read_local_config_values,
    get_config,
    get_config_with_sources,
    get_credential_scope_hash,
    get_cache_max_bytes,
    get_cache_ttl_seconds,
    get_doc_parsing_model,
    get_endpoint_origin,
    get_max_chunk_workers,
    get_max_pages_per_request,
    get_task_timeout_seconds,
    get_asset_total_timeout_seconds,
    get_max_asset_count,
    get_max_asset_total_bytes,
    metric_add,
    resolve_access_token,
    resolve_api_url,
)
from input_files import (
    _detect_file_type,
    _load_file_as_base64,
    _magic_matches_file_type,
)
from ocr_client import (
    _bounded_post,
    _make_api_request,
    _redact_secret,
    _retry_sleep_seconds,
    json_dumps_stable,
    parse_document,
)
from response_parser import (
    _error,
    _extract_markdown_assets,
    _extract_text,
    _is_explicit_blank_page,
    _page_identifier,
    _validate_page_coverage,
    error_result,
)
